import { CatalogItem, Match, Participant } from '@/types';

// ─── Dummy Participants ────────────────────────────────────
export const DUMMY_PARTICIPANTS: Participant[] = [
  {
    id: 'p1',
    sessionId: 's1',
    deviceId: 'd1',
    nickname: 'MovieBuff',
    avatarSeed: 1,
    isHost: true,
    swipeProgress: 12,
    joinedAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    sessionId: 's1',
    deviceId: 'd2',
    nickname: 'CinemaFan',
    avatarSeed: 2,
    isHost: false,
    swipeProgress: 8,
    joinedAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    sessionId: 's1',
    deviceId: 'd3',
    nickname: 'FilmNerd',
    avatarSeed: 3,
    isHost: false,
    swipeProgress: 15,
    joinedAt: new Date().toISOString(),
  },
  {
    id: 'p4',
    sessionId: 's1',
    deviceId: 'd4',
    nickname: 'PopcornQueen',
    avatarSeed: 4,
    isHost: false,
    swipeProgress: 10,
    joinedAt: new Date().toISOString(),
  },
];

// ─── Dummy Catalog (Swipe Deck) ───────────────────────────
export const DUMMY_CATALOG: CatalogItem[] = [
  {
    id: 'c1',
    sessionId: 's1',
    tmdbId: 693134,
    title: 'Dune: Part Two',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nez7S.jpg',
    synopsis: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.',
    genres: ['Sci-Fi', 'Adventure'],
    runtime: 166,
    releaseYear: 2024,
    tmdbRating: 8.8,
    availableOn: ['netflix'],
    displayOrder: 1,
  },
  {
    id: 'c2',
    sessionId: 's1',
    tmdbId: 603,
    title: 'The Matrix',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    synopsis: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    genres: ['Action', 'Sci-Fi'],
    runtime: 136,
    releaseYear: 1999,
    tmdbRating: 8.7,
    availableOn: ['max'],
    displayOrder: 2,
  },
  {
    id: 'c3',
    sessionId: 's1',
    tmdbId: 27205,
    title: 'Inception',
    posterUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    synopsis: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    genres: ['Sci-Fi', 'Thriller'],
    runtime: 148,
    releaseYear: 2010,
    tmdbRating: 8.4,
    availableOn: ['netflix', 'prime'],
    displayOrder: 3,
  },
  {
    id: 'c4',
    sessionId: 's1',
    tmdbId: 157336,
    title: 'Interstellar',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    synopsis: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    genres: ['Sci-Fi', 'Adventure'],
    runtime: 169,
    releaseYear: 2014,
    tmdbRating: 8.6,
    availableOn: ['paramount'],
    displayOrder: 4,
  },
  {
    id: 'c5',
    sessionId: 's1',
    tmdbId: 550,
    title: 'Fight Club',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    synopsis: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    genres: ['Drama', 'Thriller'],
    runtime: 139,
    releaseYear: 1999,
    tmdbRating: 8.4,
    availableOn: ['hulu'],
    displayOrder: 5,
  },
  {
    id: 'c6',
    sessionId: 's1',
    tmdbId: 238,
    title: 'The Godfather',
    posterUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    synopsis: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.',
    genres: ['Crime', 'Drama'],
    runtime: 175,
    releaseYear: 1972,
    tmdbRating: 8.7,
    availableOn: ['paramount', 'prime'],
    displayOrder: 6,
  },
  {
    id: 'c7',
    sessionId: 's1',
    tmdbId: 155,
    title: 'The Dark Knight',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BTUgMe1nqB8J.jpg',
    synopsis: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.',
    genres: ['Action', 'Crime', 'Drama'],
    runtime: 152,
    releaseYear: 2008,
    tmdbRating: 9.0,
    availableOn: ['max'],
    displayOrder: 7,
  },
  {
    id: 'c8',
    sessionId: 's1',
    tmdbId: 680,
    title: 'Pulp Fiction',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    synopsis: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    genres: ['Crime', 'Thriller'],
    runtime: 154,
    releaseYear: 1994,
    tmdbRating: 8.5,
    availableOn: ['netflix', 'paramount'],
    displayOrder: 8,
  },
  {
    id: 'c9',
    sessionId: 's1',
    tmdbId: 120,
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    posterUrl: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    synopsis: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth.',
    genres: ['Fantasy', 'Adventure'],
    runtime: 178,
    releaseYear: 2001,
    tmdbRating: 8.8,
    availableOn: ['max'],
    displayOrder: 9,
  },
  {
    id: 'c10',
    sessionId: 's1',
    tmdbId: 244786,
    title: 'Whiplash',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    synopsis: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.',
    genres: ['Drama', 'Music'],
    runtime: 107,
    releaseYear: 2014,
    tmdbRating: 8.5,
    availableOn: ['netflix'],
    displayOrder: 10,
  },
];

// ─── Dummy Matches (Results) ──────────────────────────────
export const DUMMY_MATCHES: Match[] = [
  {
    catalogItemId: 'c2',
    title: 'The Matrix',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    tmdbRating: 8.7,
    availableOn: ['max'],
    genres: ['Action', 'Sci-Fi'],
    runtime: 136,
    releaseYear: 1999,
    synopsis: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    rightSwipeCount: 4,
    totalParticipants: 4,
    matchPercentage: 1.0,
    tier: 'perfect',
    avgEnthusiasm: 1200,
  },
  {
    catalogItemId: 'c3',
    title: 'Inception',
    posterUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    tmdbRating: 8.4,
    availableOn: ['netflix', 'prime'],
    genres: ['Sci-Fi', 'Thriller'],
    runtime: 148,
    releaseYear: 2010,
    synopsis: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    rightSwipeCount: 3,
    totalParticipants: 4,
    matchPercentage: 0.75,
    tier: 'strong',
    avgEnthusiasm: 1800,
  },
  {
    catalogItemId: 'c4',
    title: 'Interstellar',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    tmdbRating: 8.6,
    availableOn: ['paramount'],
    genres: ['Sci-Fi', 'Adventure'],
    runtime: 169,
    releaseYear: 2014,
    synopsis: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    rightSwipeCount: 2,
    totalParticipants: 4,
    matchPercentage: 0.5,
    tier: 'soft',
    avgEnthusiasm: 2400,
  },
  {
    catalogItemId: 'c7',
    title: 'The Dark Knight',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BTUgMe1nqB8J.jpg',
    tmdbRating: 9.0,
    availableOn: ['max'],
    genres: ['Action', 'Crime', 'Drama'],
    runtime: 152,
    releaseYear: 2008,
    synopsis: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.',
    rightSwipeCount: 3,
    totalParticipants: 4,
    matchPercentage: 0.75,
    tier: 'strong',
    avgEnthusiasm: 1500,
  },
];

// ─── Avatar URLs (using UI Faces style placeholders) ──────
export const AVATAR_URLS = [
  'https://i.pravatar.cc/100?img=1',
  'https://i.pravatar.cc/100?img=2',
  'https://i.pravatar.cc/100?img=3',
  'https://i.pravatar.cc/100?img=4',
  'https://i.pravatar.cc/100?img=5',
];
